# OpenTelemetry Collector Configuration for CI Testing
receivers:
  # OTLP receiver accepts metrics and traces via gRPC and HTTP protocols
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 500

  # File exporter for traces only
  file/traces:
    path: /collector-logs/traces.json
    format: json

  # File exporter for metrics only
  file/metrics:
    path: /collector-logs/metrics.json
    format: json

extensions:
  # Health check extension to monitor collector's health status for CI
  health_check:
    endpoint: 0.0.0.0:13133

service:
  # Telemetry configuration for collector's own logs (internal logging)
  telemetry:
    logs:
      level: debug
      encoding: json
      output_paths: ['/collector-logs/collector-logs.json']

  # Enable extensions
  extensions: [health_check]

  # Processing pipelines define data flow from receivers through processors to exporters
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug, file/traces]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug, file/metrics]
