receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
    timeout: 5s

  resource:
    attributes:
      # Not using gcp detector to avoid increasing time series due to changing instance IDs in Cloud Run.
      - key: 'location'
        value: 'us-east1' # Set the location to your Google Cloud region
        action: upsert

exporters:
  googlecloud:
  googlemanagedprometheus:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [googlemanagedprometheus]
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [googlecloud]
