name: Example Workflow 03

on:
  push:

jobs:
  example-app:
    name: Example Application Pipeline
    uses: ./.github/workflows/example-app-workflow.yml
    with:
      fixed-sleep: 3
      random-sleep: 3
