name: Example Workflow 02

on:
  push:
    branches:
      - main
      - getting-started

jobs:
  example-app:
    name: Example Application Pipeline
    uses: ./.github/workflows/example-app-workflow.yml
    with:
      fixed-sleep: 2
      random-sleep: 3
